# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem6_GeneratedSolution as module_0
import builtins as module_1


def test_case_0():
    bool_0 = False
    list_0 = [bool_0, bool_0, bool_0, bool_0, bool_0]
    var_0 = module_0.fourSum(list_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "v\t'1t$z"
    module_0.fourSum(str_0, str_0)


def test_case_2():
    bool_0 = True
    list_0 = [bool_0, bool_0, bool_0, bool_0, bool_0]
    var_0 = module_0.fourSum(list_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -681
    bool_0 = False
    list_0 = [bool_0, int_0, bool_0, bool_0, bool_0]
    var_0 = module_0.fourSum(list_0, bool_0)
    module_1.object(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = -707
    bool_0 = False
    list_0 = [bool_0, int_0, bool_0, bool_0, int_0, bool_0]
    var_0 = module_0.fourSum(list_0, bool_0)
    module_0.fourSum(bool_0, var_0)


def test_case_5():
    int_0 = 1086
    bool_0 = False
    list_0 = [bool_0, int_0, bool_0, bool_0, int_0, bool_0]
    var_0 = module_0.fourSum(list_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    int_0 = 8
    bool_0 = False
    list_0 = [bool_0, int_0, bool_0, bool_0]
    var_0 = module_0.fourSum(list_0, int_0)
    none_type_0 = None
    module_0.fourSum(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    int_0 = 8
    bool_0 = False
    list_0 = [bool_0, int_0, bool_0, bool_0, int_0, int_0, int_0, bool_0]
    var_0 = module_0.fourSum(list_0, bool_0)
    var_1 = module_0.fourSum(list_0, int_0)
    module_0.fourSum(bool_0, var_0)
